name: github action

on:
  push:
    branches:
      - master # Trigger the deployment only when there is a push to the master branch (after PR is merged)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: npm install
        run: npm ci
      - name: tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref == 'refs/heads/master' # Ensures that deployment runs only when merged to the 'master' branch

    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.13.15 # This is the action # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "github-actions-node-test"
          heroku_email: "ruth.co.264@gmail.com"
